# Generated by Django 4.2 on 2023-04-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total', models.BinaryField()),
                ('processedText', models.CharField(max_length=5000)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.storage')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('KL', 'Kilos'), ('GR', 'Grams'), ('UN', 'Unitats'), ('PK', 'Paquets'), ('LI', 'Litres'), ('OT', 'Altres')], max_length=2)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.storage')),
            ],
        ),
    ]
