# Generated by Django 4.2 on 2023-04-08 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_storage_users_delete_userstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('UN', 'Unitats'), ('PI', 'Peces'), ('KL', 'Kilos'), ('GR', 'Grams'), ('PK', 'Paquets'), ('LI', 'Litres'), ('OT', 'Altres')], default='OT', max_length=2),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('name_clear', models.CharField(max_length=400)),
                ('price', models.BinaryField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.ticket')),
            ],
        ),
    ]
