# Generated by Django 4.2 on 2023-04-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_alter_item_unit_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
    ]
