# Generated by Django 4.2 on 2023-04-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_remove_ticket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total',
            field=models.FloatField(),
        ),
    ]
